version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: cameratrap-django-container
    image: cameratrap-django-image
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../ct22-volumes/static:/ct22-volumes/static
      - ../ct22-volumes/media:/ct22-volumes/media
      - ../ct22-volumes/bucket:/bucket
      - ../ct22-volumes/logs/ct-web:/var/log/ct-web
    command: /srv/start
    restart: no
    #env_file:
    #  - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  postgres:
    #image: postgres:13-alpine
    shm_size: '1g'
    build:
      context: ./docker
      dockerfile: Dockerfile_postgres
    image: cameratrap-postgres-image
    container_name: cameratrap-postgres-container
    volumes:
      - ../ct22-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../ct22-volumes/bucket:/bucket
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
      - PGDATA=/var/lib/postgresql/data/pgdata
    #env_file:
    #  - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  redis:
    image: redis:6-alpine
    restart: no
  celery:
    restart: unless-stopped
    container_name: cameratrap-celery-container
    image: cameratrap-django-image
    command: celery -A conf worker -l info -c 1
    volumes:
      - .:/code
      - ../ct22-volumes/media:/ct22-volumes/media
      - ../ct22-volumes/logs/ct-web:/var/log/ct-web
    depends_on:
      - redis
      - django
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  flower:
    restart: unless-stopped
    container_name: cameratrap-flower-container
    image: cameratrap-django-image
    ports:
      - 5555:5555
    command: celery flower -persisten=True --port=5555
    volumes:
      - .:/code
      - ../ct22-volumes/media:/ct22-volumes/media
      - ../ct22-volumes/logs/ct-web:/var/log/ct-web
    depends_on:
      - redis
      - django
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
      - CELERY_BROKER_URL=redis://redis:6379/3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
