version: "3.7"

services:
  django:
    ports:
      - 8000:8000
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
  slack_bot:
    build:
      context: ./slack_bot
      dockerfile: Dockerfile
    container_name: cameratrap-slack-bot-container
    image: cameratrap-slack-bot-image
    env_file:
      - ./slack_bot/.env
    volumes:
      - ../ct22-volumes/duckdb:/data:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"