#FROM postgres:13-alpine
FROM postgres:13-bookworm

# install postgis for shp2pgsql
RUN apt-get update \
      && apt-get install -y --no-install-recommends \
          postgresql-13-postgis-3 \
          postgresql-13-postgis-3-scripts \
          postgis \
      && rm -rf /var/lib/apt/lists/*

#COPY *.sql.gz /docker-entrypoint-initdb.d/
