# Generated by Django 4.0.4 on 2023-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0040_remove_deletedimage_count_remove_deletedimage_exif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='desktop_login',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
