# Generated by Django 4.0.4 on 2023-10-16 21:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0041_contact_desktop_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedAreaBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('area_class', models.CharField(max_length=500)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
