# Generated by Django 4.0.4 on 2024-02-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0042_namedareaborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='calculation',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taicat.deployment'),
        ),
        migrations.AlterField(
            model_name='deploymentjournal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_list', to='taicat.project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taicat.project'),
        ),
        migrations.AlterField(
            model_name='projectspecies',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_list', to='taicat.project'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stat', to='taicat.project'),
        ),
    ]
