# Generated by Django 4.0.4 on 2024-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0043_infolog_alter_calculation_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_duplicated',
            field=models.CharField(blank=True, default='N', max_length=2),
        ),
    ]
