# Generated by Django 4.0.4 on 2024-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0044_image_is_duplicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_duplicated',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
