# Generated by Django 4.0.4 on 2024-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0045_alter_image_is_duplicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedimage',
            name='is_duplicated',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
