# Generated by Django 4.0.4 on 2024-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0046_deletedimage_is_duplicated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_id', models.IntegerField()),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('project', models.CharField(max_length=1000, null=True)),
                ('studyarea', models.CharField(max_length=1000, null=True)),
                ('deployment', models.CharField(max_length=1000, null=True)),
                ('species', models.CharField(max_length=1000, null=True)),
                ('life_stage', models.CharField(max_length=1000, null=True)),
                ('sex', models.CharField(max_length=1000, null=True)),
                ('antler', models.CharField(max_length=1000, null=True)),
                ('animal_id', models.CharField(max_length=1000, null=True)),
                ('remark', models.TextField(default='', null=True)),
                ('modified_datetime', models.DateTimeField(null=True)),
                ('modified_project', models.CharField(max_length=1000, null=True)),
                ('modified_studyarea', models.CharField(max_length=1000, null=True)),
                ('modified_deployment', models.CharField(max_length=1000, null=True)),
                ('modified_species', models.CharField(max_length=1000, null=True)),
                ('modified_life_stage', models.CharField(max_length=1000, null=True)),
                ('modified_sex', models.CharField(max_length=1000, null=True)),
                ('modified_antler', models.CharField(max_length=1000, null=True)),
                ('modified_animal_id', models.CharField(max_length=1000, null=True)),
                ('modified_remark', models.TextField(default='', null=True)),
            ],
        ),
    ]
