# Generated by Django 4.0.4 on 2024-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0046_deploymentjournal_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='client_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deploymentjournal',
            name='client_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deploymentjournal',
            name='num_of_images',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
