# Generated by Django 4.0.4 on 2024-07-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0047_modifiedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedimage',
            old_name='modified_remark',
            new_name='modified_remarks',
        ),
        migrations.RenameField(
            model_name='modifiedimage',
            old_name='remark',
            new_name='remarks',
        ),
    ]
