# Generated by Django 4.2 on 2024-08-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0047_deploymentjournal_client_hostname_and_more'),
        ('taicat', '0049_modifiedimage_project_id_modifiedimage_studyarea_id'),
    ]

    operations = [
    ]
