# Generated by Django 4.2 on 2024-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0050_merge_20240827_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='action_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
