# Generated by Django 4.2 on 2025-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0052_alter_deployment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='upload_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
