# Generated by Django 4.2 on 2026-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0053_deploymentjournal_upload_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedimage',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
