# Generated by Django 4.2 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0054_modifiedimage_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='media_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
