# Generated by Django 4.2 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0055_image_media_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedimage',
            name='media_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
