# Generated by Django 4.2 on 2026-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0056_deletedimage_media_uploaded_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(condition=models.Q(('annotation_seq__gt', 0)), fields=['deployment_journal', 'filename'], name='taicat_image_journal_filename'),
        ),
    ]
