# Generated by Django 4.0.4 on 2024-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_mod_date_announcement_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
